baseURL = 'skpack-manual/'
canonifyURLs = true
title = 'SK PACK Manual'

[markup]
[markup.goldmark]
[markup.goldmark.parser.attribute]
block = true
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
# See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
style = "tango"
# Uncomment if you want your chosen highlight style used for code blocks without a specified language
# guessSyntax = "true"

[[menu.main]]
name = "Admin page"
weight = 100
url = "https://skpack.co.kr/admin"
post = " <i class='fa fa-2xs fa-arrow-up-right-from-square'></i>"

[params]
copyright = "The Docsy Authors"
#privacy_policy = "https://policies.google.com/privacy"

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.developer]]
name = "Admin page"
url = "https://skpack.co.kr/admin"
icon = "fa fa-gear"
desc = "Go to admin page"
[[params.links.developer]]
name = "Home page"
url = "https://skpack.co.kr"
icon = "fa fa-house"
desc = "Go to home page"

staticDir = ['static']

# hugo module configuration
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
